spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          trusted-proxies: ".*"

          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
            - id: department-service
              uri: lb://DEPARTMENT-SERVICE
              predicates:
                - Path=/department/**
              filters:
                - StripPrefix=1
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

server:
    port: 9196
    forward-headers-strategy: framework

eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      registry-fetch-interval-seconds: 5
      service-url:
        defaultZone: http://service-registry:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      departmentService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
      access: read-only

  metrics:
    tags:
      application: ${spring.application.name}



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /user/v3/api-docs

      - name: Department Service
        url: /department/v3/api-docs