spring.main.allow-bean-definition-overriding=true
jwt.secret=your-super-secret-key-for-development-only-change-this-later
jwt.expiration=3600000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2.server.resource=DEBUG
logging.level.org.springframework.security.oauth2.jwt=DEBUG